name: CI
on: [push]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Cache browsers
        id: cache-browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-browsers-${{ hashFiles('**/yarn.lock') }}

      - name: Install Playwright
        if: steps.cache-browsers.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps

      - name: Test
        run: yarn test

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: playwright-report/
          retention-days: 30

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        working-directory: dist
        run: |
          git init
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git checkout -b main
          git add -A
          git commit -m 'deploy'
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} main:gh-pages
